[build]
  command = "npm ci && npx expo export --platform web"
  publish = "dist"

[[redirects]]
  from = "/livepay"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/livepay/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
